### ISSUE TITLE
Detection limit EARs

### ISSUE THREAD

**Issue by srcorsi-USGS** [ldecicco-USGS/passive_tox#10]
Do we have an SI figure that has the EAR levels at the detection limits? I can write about the implications once I see that.

**Comment by ldecicco-USGS** [comment]
I made a graph this summer that's here:

https://doimspp-my.sharepoint.com/personal/srcorsi_usgs_gov/_layouts/15/onedrive.aspx?id=%2fpersonal%2fsrcorsi_usgs_gov%2fDocuments%2fGLRI+CECs%2fPhase+I%2fPassive%2fManuscript%2fSupplemental&FolderCTID=0x012000A09D88CFE962D44B98344DAF211A723D

with:
https://github.com/ldecicco-USGS/passive_tox/blob/master/explore_detection_limits.R

I just re-did the script though (because I didn't notice until I saved a new plot). 
https://github.com/ldecicco-USGS/passive_tox/blob/master/explore_detection_limits_NEW.R
I think this way is cleaner and makes more sense (and uses toxEval features that didn't exist earlier)
